import { ColorTheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createStyles = (colors: ColorTheme) => {
  return StyleSheet.create({
    modalContent: {
      backgroundColor: colors.surface,
      padding: 24,
      borderRadius: 20,
      width: "85%",
      maxWidth: 400,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      paddingHorizontal: 20,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      marginBottom: 20,
      color: colors.text,
      textAlign: "center",
    },
    modalInput: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
      color: colors.text,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderWidth: 2,
      borderRadius: 12,
      marginBottom: 24,
      fontSize: 16,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    modalButtonsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    modalCancelButton: {
      backgroundColor: colors.surface,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: "center",
      flex: 1,
      borderWidth: 2,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    modalButton: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: "center",
      flex: 1,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    modalButtonText: {
      color: colors.surface,
      fontSize: 16,
      fontWeight: "700",
    },
    modalCancelButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "700",
    },
  });
};
